name: demo

on:
  push:
    branches:
      - main
      - develop
      - cicd
      - update
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cài đặt trình biên dịch (Ubuntu có sẵn gcc nhưng ta cài cho chắc)
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # 3. Build (biên dịch main.c thành file thực thi main)
      - name: Build
        run: |
          echo "🔧 Đang biên dịch code C..."
          gcc main.c -o main

      # 4. Test (chạy file vừa build ra)
      - name: Run tests
        run: |
          echo "🧪 Đang chạy test..."
          ./main
