name: demo

on:
  push:
    branches:
      - main
      - develop
      - cicd
      - update
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Chạy một lệnh kiểm tra đơn giản
      - name: Run build step
        run: |
          echo "✅ Workflow đang chạy trên nhánh: $GITHUB_REF"
          echo "👉 Bạn có thể thêm các lệnh build/test của ngôn ngữ bạn đang dùng tại đây."
