name: demo CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Bước 3: Cài đặt Yarn hoặc npm
      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      # Bước 4: Đăng nhập vào Expo
      - name: Expo Login
        run: |
          expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      # Bước 5: Build + Publish lên Expo
      - name: Build and publish to Expo
        run: |
          expo publish --non-interactive
